apps/bureau_web/lib/bureau_web/router.ex
defmodule BureauWeb.Router do
  use BureauWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BureauWeb.Plug.Session
  end

  pipeline :user do
    plug BureauWeb.User.Pipeline
  end

  pipeline :employer do
    plug BureauWeb.Employer.Pipeline
  end

  pipeline :admin do
    plug BureauWeb.Admin.Pipeline
    plug :put_layout, {BureauWeb.LayoutAdminView, :admin}
    # Apply admin layout at the router level
    # https://cultivatehq.com/posts/how-to-set-different-layouts-in-phoenix/
  end

  scope "/", BureauWeb do
    pipe_through [:browser]

    get "/", PageController, :index

    # password reset
    get "/incanto/password", SessionController, :password
    post "/incanto/password", SessionController, :reset_pswrd

    # login
    resources "/incanto", SessionController, only: [:index, :create]
  
    # users
    get "/alchemists/authorize", UserController, :authorize
    get "/alchemists/join", UserController, :new

    get "/alchemists/password", UserController, :password
    post "/alchemists/password", UserController, :update_password

    resources "/alchemists", UserController, only: [:index, :create]

    scope "/alchemists" do
      pipe_through [:user]
  
      get "/enchant", UserController, :enchant
      put "/enchant", UserController, :update
      delete "/retirement", UserController, :delete
  
      # logout
      delete "/logout", UserController, :logout
    end

    get "/alchemists/:username", UserController, :show

    # job offers
    get "/jobs/authorize", JobController, :authorize
    resources "/jobs", JobController, only: [:index, :show, :new, :create]

    # job owners area
    scope "/jobs" do
      pipe_through [:employer]
  
      delete "/close", JobController, :close
    end
  
    # admin area
    resources "/admin/login", AdminSessionController, only: [:index, :create]
    
    scope "/admin" do
      pipe_through [:admin]
  
      get "/dashboard", DashboardController, :index
      resources "/users", AdminUserController, only: [:index, :show, :update, :delete]
      resources "/jobs", AdminJobController, only: [:index, :show, :update, :delete]
  
      delete "/logout", AdminSessionController, :delete
    end

    get "/*path", PageController, :not_found
  end
end

apps/bureau_web/lib/bureau_web/templates/layout_admin/admin.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="author" content="">
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href='<%= Routes.static_path(@conn, "/admin/css/bootstrap.min.css") %>'>
    <link rel="stylesheet" href='<%= Routes.static_path(@conn, "/admin/css/light-bootstrap-dashboard.css") %>'>    
    <link rel="stylesheet" href='<%= Routes.static_path(@conn, "/admin/css/pe-icon-7-stroke.css") %>'>
   
    <title>Dashboard</title>
</head>
<body>
  <div class="wrapper">
    <div class="sidebar" data-color="purple">
    	<div class="sidebar-wrapper">
            <div class="logo">
                <a class="simple-text">
                    <%= Guardian.Plug.current_resource(@conn)["name"] %>
                </a>
            </div>

            <ul class="nav">
                <li class="<%= active_class?(@conn.request_path, "dashboard") %>">
                    <%= link("Dashboard", to: Routes.dashboard_path(@conn, :index), method: :get)%>
                </li>
                <li class="<%= active_class?(@conn.request_path, "users") %>">
                    <%= link("Users", to: Routes.admin_user_path(@conn, :index), method: :get)%>
                </li>
                <li class="<%= active_class?(@conn.request_path, "jobs") %>">
                    <%= link("Jobs", to: Routes.admin_job_path(@conn, :index), method: :get)%>
                </li>
            </ul>
    	</div>
    </div>

        <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><%= title(@conn.request_path) %></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <%= link("Logout", to: Routes.admin_session_path(@conn, :delete), method: :delete)%>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <main role="main" class="content">
      <%= render @view_module, @view_template, assigns %>
    </main>

  </div>
</div>
</body>
    <!-- phoenix_html.js need to make link delete working properly! -->
  <script src='<%= Routes.static_path(@conn, "/admin/js/phoenix_html.js") %>' type="text/javascript"></script>
  <script src='<%= Routes.static_path(@conn, "/admin/js/jquery.3.2.1.min.js") %>' type="text/javascript"></script>
  <script src='<%= Routes.static_path(@conn, "/admin/js/bootstrap.min.js") %>' type="text/javascript"></script>
  <script src='<%= Routes.static_path(@conn, "/admin/js/light-bootstrap-dashboard.js") %>' type="text/javascript"></script>
  
</html>